add: 구조 분해 할당 정리
gdsc-ssu/hcj-study pull request #16
Opened 2022-11-12 11:57 UTC by hongSso

## Summary
자바스크립트에서 유용하게 사용되는 구조 분해 할당에 대해서 정리해봤습니다!! 

## Check List
- [X] PR 제목을 commit convention에 맞게 작성
- [X] Assignees 추가
- [X] label 추가

2022-11-25 06:01 UTC, kanghyun98 requested changes
구조분해할당 관련해서 많은 내용들이 들어가 있어서 좋은 것 같아요!
고생 많으셨습니다! 

주석 바뀐게 하나 있어서 수정 부탁드릴게요~

2022-11-25 06:01 UTC, kanghyun98 commented on Javascript/destructuring-assignment.md
> +    var [firstName, lastName] = arr;
ES6+에서는 `var`보다는 `const` or `let`을 사용하는 방식을 지향하면 더 좋을 것 같아요!
물론 단순 예제라 크게 상관 없을 수 있지만,, 참고해주세요!ㅎ

2022-11-25 06:01 UTC, kanghyun98 commented on Javascript/destructuring-assignment.md
> +    var [firstName, lastName] = arr;
관련 내용해서 궁금하시면 수진님이 작성해주신 [var, let, const 비교 설명 자료](https://github.com/gdsc-ssu/hcj-study/pull/5)을 확인하시면 좋을 것 같습니다!

2022-11-25 06:01 UTC, kanghyun98 commented on Javascript/destructuring-assignment.md
> +    //배열 요소를 구조 분해 할당 방식을 사용할 때
주석이 위에꺼랑 바뀌었어요!!

2022-11-25 06:01 UTC, kanghyun98 commented on Javascript/destructuring-assignment.md
> +    변수에 값을 할당하게 되면 나중에 기존에 있던 값보다 할당되는 값을 우선으로 한다.
"나중에"는 지워도 될 것 같아요!

2022-11-25 06:01 UTC, kanghyun98 commented on Javascript/destructuring-assignment.md
> +    ```
오 이런게 되는줄은 몰랐네요!! 하나 배워갑니다~~

2022-11-25 06:01 UTC, kanghyun98 commented on Javascript/destructuring-assignment.md
> +    ```
객체의 구조분해할당의 경우 "할당의 기준은 순서가 의미 없으며, 선언된 변수 이름과 프로퍼티 키가 일치하면 할당된다." 라는 설명이 추가되면 좋을 것 같아요!!

2022-11-26 18:31 UTC, kweonsikyung approved these changes
구조분해할당은 은근 많이 쓰는데 swap이 되는줄은 몰랐어요, 소연님 덕분에 알아가요. 감사합니다!!

2022-12-25 18:52 UTC, hongSso commented on Javascript/destructuring-assignment.md
> +    var [firstName, lastName] = arr;
수진님 자료 읽고 차이점을 잘 이해했습니다! 감사합니다 :)

2022-12-25 18:52 UTC, hongSso commented on Javascript/destructuring-assignment.md
> +    //배열 요소를 구조 분해 할당 방식을 사용할 때
수정했습니다!

2022-12-25 18:53 UTC, hongSso commented on Javascript/destructuring-assignment.md
> +    ```
내용을 추가하니 읽기가 더 편해졌네요! 감사합니다 :-)

2023-01-04 09:39 UTC, kanghyun98 approved these changes

2023-01-04 09:40 UTC, merged