Javascript/iframe
gdsc-ssu/hcj-study pull request #21
Opened 2022-11-19 14:57 UTC by kweonsikyung

## Summary

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] Assignees 추가
- [ ] label 추가

2022-11-23 09:01 UTC, SujinKim1127 commented
iframe 에서는 태그를 `margin-height` 말고 `marginheight` 이렇게 `-`를 빼고 사용을 하는데 그 이유가 뭔지 혹시 아시나요?? 뭔가 가독성은 `-`가 들어간게 더 좋아보이는데 왜 빼고 쓰는지 궁금해졌어요..

2022-11-26 11:27 UTC, kanghyun98 approved these changes
iframe을 따로 공부해본적이 없었는데, 이것저것 많이 보고 배워갑니다!
고생하셨어요😄

2022-11-26 11:31 UTC, kanghyun98 requested changes
앗 그런데 파일이 html 디렉토리에 있습니다!
옮기는 커밋 추가해주시면 좋을 것 같아요:)

2022-11-26 14:25 UTC, ryuseunghan commented
크롬익스텐션으로 스마트캠퍼스 개선하기 세미나를 들으며 궁금했던 iframe에 관하여 정리해주신 자료를 보고 많이 배워갈 수 있었습니다! 감사합니다!

2022-11-26 14:52 UTC, hongSso requested changes
iframe에 대해서 깊에 공부해보지 않았는데 정리된 자료를 토대로 frame과 iframe과 frameset까지 찾아보면서 공부가 많이 됐습니다! 태그 옵션까지 꼼꼼히 정리해주셔서 하나하나 잘 봤습니다!✨

2022-11-26 14:52 UTC, hongSso commented on HTML/iframe.md
> ++ video 태그는 동영상 자체에 인터페이스가 없으므로 controls을 활용하여 인터페이스를 추가하나, iframe 유튜브 동영상의 경우 동영상 자체에 인터페이스가 있으므로 controls 옵션을 사용하여 인터페이스를 제거해줌,)
커트롤 -> 컨트롤 오타있습니다! 그리고 43에 ,)도 수정해주면 좋을 것 같아요~~

2022-11-26 18:45 UTC, kweonsikyung commented on HTML/iframe.md
> ++ video 태그는 동영상 자체에 인터페이스가 없으므로 controls을 활용하여 인터페이스를 추가하나, iframe 유튜브 동영상의 경우 동영상 자체에 인터페이스가 있으므로 controls 옵션을 사용하여 인터페이스를 제거해줌,)
으악 감사합니다!!!

2022-11-26 18:46 UTC, closed without merging