Javascript/regular expression regex
gdsc-ssu/hcj-study pull request #4
Opened 2022-10-29 12:25 UTC by kweonsikyung

## Summary
PR 연습 중입니다... 
내용은 곧 추가하겠습니다*^^*

## Check List

- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] reviewers 추가
- [ ] label 추가

2022-11-07 16:16 UTC, ballsona requested changes
오 내용 구성이 되게 깔끔한 것 같아요! 마크다운이 익숙하지 않은 상태에서 정리해주시느라 고생하셨어요 ㅠㅠ
다만.. 머지 하시기 전에 함께 커밋해주신 이미지 파일들은 깃허브 이슈를 통해 링크로 변환 후 마크다운 내 이미지들을 링크 형태로 교체하고 파일은 삭제하는 과정이 필요할 것 같아요,,,! 혹시 도움이 필요하시면 저한테 언제든지 디엠주세요 !! 👍

2022-11-07 17:28 UTC, kweonsikyung commented
@ballsona 넵 이미지 파일 수정했습니다!! 감사합니다!!!!

2022-11-26 13:50 UTC, hongSso requested changes
항상 정규표현식이 필요할 때 구글링만 해서 복붙했는데,,,, 덕분에 여러 규칙들 많이 알아갑니다! 직접 정규식을 작성하려면 연습이 많이 필요하겠지만 보면서 따라하면 필요한 정규표현식을 직접 작성할 수 있을 것 같아요! 주요 메서드들도 잘 봤습니다! :-)

2022-11-26 13:50 UTC, hongSso commented on Javascript/regular-expression.md
> +
감사진 -> 감싸진 오타있습니다!

2023-02-28 11:50 UTC, closed without merging