add: JS array정리
gdsc-ssu/hcj-study pull request #8
Opened 2022-11-06 14:20 UTC by hoyyChoi

## Summary
js에서 유용하게 쓰이는 array 내장함수를 정리해봤습니다.

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] reviewers 추가
- [ ] label 추가

2022-11-07 06:40 UTC, kanghyun98 requested changes
스터디의 첫번째 PR..!! 축하드립니다!ㅋㅋㅋ
array 정리글 잘 봤습니다. 고생하셨어요:)
오타 몇개만 수정해주시면 될 것 같구, `.DS_STORE` 파일이 추가되어있던데 이거는 꼭 삭제해주세여..!!!

2022-11-07 06:40 UTC, kanghyun98 commented on Javascript/array(배열).md
> +2. 배열 요소의 인댁스가 연속적이지 않아도 되며, 따라서 특정 배열 요소가 비어 있을 수 있다.
오타있습니다!
댁 -> 덱

2022-11-07 06:40 UTC, kanghyun98 commented on Javascript/array(배열).md
> +```
음 ES6+에서는 `var` 사용을 지양하는게 좋습니다만,,
단순 예시니깐 크게 상관 없을 것 같긴해요!
담에 작성할 때는 되도록이면 `let`, `const`의 사용을 권장드립니다!!ㅎ

2022-11-07 06:40 UTC, kanghyun98 commented on Javascript/array(배열).md
> +- 배열을 다룰 때 유요한 내장 함수
오타 있는 것 같습니다!

2022-11-07 06:40 UTC, kanghyun98 commented on Javascript/array(배열).md
> +- map 은 배열 안의 각 원소를 변환 할 때 사용 되며, **이 과정에서 새로운 배열이 만들어진다.**→ 그러므로 빈배열에 넣는 것이 안되고 새로운 상수값에 재할당을 해야한다.
**이 과정에서 새로운 배열이 만들어진다.**→
여기서 md 파싱이 제대로 동작 안한 것 같습니다!
화살표를 한칸 띄어서 작성하면 의도하신대로 정상적으로 작동하니 수정하시면 될 것 같아요!

2022-11-07 06:40 UTC, kanghyun98 commented on Javascript/array(배열).md
> +console.log(squared);
출력 결과 같이 보여주시면 더 좋을 것 같아요!

2022-11-07 06:40 UTC, kanghyun98 commented on Javascript/array(배열).md
> +→ splice는 인자가 2개이며, index는 제거를 시작할 부분을 말하고,. 1은 몇개를 삭제할지이다.
별거 아니긴하지만,, "말하고,."에서 `.`은 없어도 될 것 같습니다!

2022-11-07 06:40 UTC, kanghyun98 commented on Javascript/array(배열).md
> +- -배열의 첫번째원소(shift)와 마지막 원소(pop)를 제거하는 함수  (기존의 배열을 건드림)
`-` 작대기 하나 더 들어갔습니다!

2022-11-07 15:16 UTC, hoyyChoi commented on Javascript/array(배열).md
> +```
알겠습니다!

2022-11-07 15:48 UTC, hoyyChoi commented
@kanghyun98 리뷰 감사합니다! 말씀하신대로 수정완료하였습니다!

2022-11-07 18:01 UTC, kanghyun98 approved these changes

2022-11-26 18:08 UTC, kweonsikyung commented
자바스크립트에도 파이썬만큼 이렇게 다양한 배열의 메소드, 함수가 있었군여..!! 덕분에 잘 알아가요 수고하셨습니다!!

2022-11-26 18:38 UTC, kweonsikyung approved these changes
자바스크립트에도 파이썬만큼 이렇게 다양한 배열의 메소드, 함수가 있었군여..!! 덕분에 잘 알아가요 수고하셨습니다!!

2023-01-01 11:42 UTC, merged